framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
#        fallbacks is when symfony can not find translation it will use fallbacks
        fallbacks:
            - '%locale%'
